export const CONTACTS_DELETE = 'CONTACTS_DELETE';
export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_CREATE = 'CONTACTS_CREATE';
export const CONTACTS_RELOAD = 'CONTACTS_RELOAD';
export const CONTACTS_FETCH = 'CONTACTS_FETCH';